### ISSUE TITLE
Calculate sum of squares till a number

### ISSUE THREAD

**Issue by RajAsapu** [RajAsapu/QA_Training#5]
Eg : 
User enters - 3
Result - 1^2+2^2+3^2=14

**Comment by vaanirao** [comment]
import java.util.Scanner;
public class Sumofsquares
{
publci static void main(Stirng args[])
{
Scanner sc= new Scanner(System.in);
System.out.println("enter number ");
int n=sc.nextInt();

- [ ] 

- [ ] System.out.println("

 entered number is :" +n);
int sum=0;
for(int x=1;x<=n;x++)
sum=sum+(x*x);
}
System.out.println(sum);
}

**Comment by RajAsapu** [comment]
@vaanirao : did you execute it ? If you did so , can you share me results .

**Comment by RajAsapu** [comment]
I correct errors from the above program : Please check the below code
`package stepdef;

import java.util.Scanner;
public class Sumofsquares
{
    public static void main(String args[])
    {
    Scanner sc= new Scanner(System.in);
    System.out.println("enter number ");
    int n=sc.nextInt();
    System.out.println("entered number is :" +n);
    int sum=0;
    for(int x=1;x<=n;x++)
    {
        sum=sum+(x*x);
    }
        System.out.println(sum);
    }
}`
